import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

export default function Home() {

  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <img className={styles.logo} src="Logo.svg" alt="" />
      <main className={styles.main}>
        <h1 className={styles.title}> </h1>
            
        <div className={styles.grid}>
          <div className={styles.card}>
            <h1 >Enter the verification code to continue </h1>
              <p className={styles.verp}>We sent to <a href=""> hajaram@gmail.com</a>. If you do not see it, check your spam</p>
              <div className={styles.boxmain}>
                 <input  type="number" max="9" Min="0" step="1" className={styles.box}/>
                 <input  type="number" max="9" Min="0" step="1" className={styles.box}/>
                 <input  type="number" max="9" Min="0" step="1" className={styles.box}/>
                 <input  type="number" max="9" Min="0" step="1" className={styles.box}/>
                 <input  type="number" max="9" Min="0" step="1" className={styles.box}/>
                 <input  type="number" max="9" Min="0" step="1" className={styles.box}/>
                
              </div>
              <button onClick={()=>{router.push("/success")}} className={styles.btn }>Submit</button>
              <div className="back">
             <a href="" onClick={()=>{router.push("/")}} className={styles.fgt}>Back</a>
              <a href="" className={styles.resend}> Resend in 0:00</a> 

              </div>
          </div> 

           <div className={styles.cardHide}>
            <div className={styles.secondpart}>
             <img src="/image.svg" alt="" className={styles.img} />
            <h6>NEW</h6>
              <h4>Developer handoff improvements</h4>
              <p>You will now see a highlight around Symbols on the Canvas and in the Inspector.</p>
            </div>
          </div>

        </div>
      </main>
         <div className={styles.signup}>Not member? <a href="">Create Account</a></div>

     
    </div>
  )
}
